# Setting Up a ROS 2 Workspace

A ROS 2 workspace is a structured directory where you can develop, build, and manage your ROS 2 packages. It's a crucial part of the ROS 2 environment as it helps you organize your code, dependencies, and build artifacts. Workspaces are essential for building and testing packages within ROS 2.

### 1. Key Concepts of a ROS 2 Workspace:
**1. Source (src) directory:** This is where all your ROS 2 packages will be stored. Each package has its own structure and set of dependencies.
**2. Build system:** ROS 2 uses colcon as the build tool for managing workspace compilation and linking.
**3. Environment setup:** After building the workspace, you source the setup file to make sure ROS 2 can find the packages and libraries within it.

### 2. ROS 2 Workspace Structure:
A ROS 2 workspace typically has the following directory structure:

```bash
my_workspace/
│
├── src/            # Source directory, contains ROS 2 packages
├── build/          # Contains build files generated by colcon (created during build process)
├── install/        # Final installed files, binaries, and executables (created during build)
└── log/            # Logs of build and run processes (created during build process)

```

### 3. Steps to Create and Use a ROS 2 Workspace
**Step 1: Creating the Workspace Directory**
Create a workspace directory and navigate into it:
```bash
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws
```
- ros2_ws is just a name for the workspace (you can name it anything).
- The -p flag in mkdir ensures that the src directory is created inside ros2_ws.

**Step 2: Adding ROS 2 Packages**
You can either clone existing ROS 2 packages from a repository into the src folder or create new packages. For example, to clone a package:

```bash
cd ~/ros2_ws/src
git clone https://github.com/ros/ros_tutorials.git

```
**Step 3: Building the Workspace**
After adding or modifying your ROS 2 packages in the src directory, you need to build them using colcon:
```bash
cd ~/ros2_ws
colcon build
```
This command will compile all the packages inside your workspace. It will generate the build/, install/, and log/ directories after the build.

**Step 4: Sourcing the Workspace**
After the workspace is built, you must source the workspace's environment so that ROS 2 can recognize the packages. This is essential if you want to run nodes or use the packages inside this workspace.
```bash
source ~/ros2_ws/install/setup.bash
```
To avoid manually sourcing the workspace every time, you can add this line to your ~/.bashrc:
```bash
echo "source ~/ros2_ws/install/setup.bash" >> ~/.bashrc
```
Now, every time you open a new terminal, your workspace will be sourced automatically.

**Step 5: Running ROS 2 Nodes from the Workspace**
Once you've sourced the workspace, you can run any ROS 2 nodes or launch files within your packages. For example, to run a node from a package called demo_nodes_cpp, you would use:
```bash
ros2 run demo_nodes_cpp talker
```
This command runs the talker node from the demo_nodes_cpp package in your workspace.

#### Example: Creating a New ROS 2 Package
Let's walk through creating a new package in your workspace.

**1. Navigate to the src directory:**
```bash
cd ~/ros2_ws/src
```
**2. Create a new package (use the ros2 pkg create command):**
```bash
ros2 pkg create my_package --build-type ament_cmake
```
This creates a new package called my_package with the ament_cmake build system.

**3. Build the workspace again:**
```bash
cd ~/ros2_ws
colcon build
```
**4.Source the workspace again:**
```bash
source ~/ros2_ws/install/setup.bash
```
Now your new package my_package is built and ready to use. You can add nodes and other functionality within this package.


# ROS 2 `ros2 pkg create` Command

The `ros2 pkg create` command is used to create a new ROS 2 package. It automatically generates the necessary files and directory structure required for a ROS 2 package, including `package.xml`, `CMakeLists.txt`, and other files depending on the build type.

## Syntax
```bash
ros2 pkg create <package_name> [OPTIONS]
```

- `<package_name>`: Name of the new ROS 2 package (required).
- `[OPTIONS]`: Optional flags and arguments to configure the package creation.

## Arguments and Options

### 1. `<package_name>`
- This is the required argument where you specify the name of the package.
- Example:
  ```bash
  ros2 pkg create my_robot_pkg
  ```

### 2. `--build-type`
- Defines the build system for the package. Common options:
  - `ament_cmake`: For C++ packages using the CMake build system.
  - `ament_python`: For Python-based packages.
- Example:
  ```bash
  ros2 pkg create my_robot_pkg --build-type ament_cmake
  ```
  or for a Python package:
  ```bash
  ros2 pkg create my_robot_pkg --build-type ament_python
  ```

### 3. `--dependencies`
- Specifies a list of dependencies that the package needs. These dependencies will be added to `package.xml` and `CMakeLists.txt` (if using CMake).
- Example:
  ```bash
  ros2 pkg create my_robot_pkg --dependencies rclcpp std_msgs
  ```

### 4. `--license`
- Specifies the license for the package. This will be included in the `package.xml` file.
- Example:
  ```bash
  ros2 pkg create my_robot_pkg --license Apache-2.0
  ```

### 5. `--description`
- Adds a description for the package, which will be included in `package.xml`.
- Example:
  ```bash
  ros2 pkg create my_robot_pkg --description "This is a package for my robot"
  ```

### 6. `--maintainer-email` and `--maintainer-name`
- These options allow you to specify the maintainer's name and email, which are included in `package.xml`.
- Example:
  ```bash
  ros2 pkg create my_robot_pkg --maintainer-email "your_email@example.com" --maintainer-name "Your Name"
  ```

## Full Example

Here is an example that combines multiple options:

```bash
ros2 pkg create my_robot_pkg --build-type ament_cmake --node-name robot_node --dependencies rclcpp std_msgs --license Apache-2.0 --maintainer-email "your_email@example.com" --maintainer-name "Your Name" --description "A package for my robot"
```

This command creates a package named `my_robot_pkg` with the following characteristics:
- C++ build system (using `ament_cmake`).
- Includes the `rclcpp` and `std_msgs` dependencies.
- Licensed under Apache 2.0.
- Maintained by "Your Name" with the specified email address.
- Describes the package as "A package for my robot".

## Directory Structure

After creating the package, the directory structure will look like this:

```
my_robot_pkg/
├── CMakeLists.txt
├── package.xml
├── src/
└── include/
```

- `CMakeLists.txt`: CMake build configuration file (for `ament_cmake`).
- `package.xml`: Package metadata including dependencies, license, and maintainer information.
- `src/` and `include/`: Directories where source code and header files (for C++) can be placed.

### Summary of Options

| Option                 | Description                                                    |
|------------------------|----------------------------------------------------------------|
| `<package_name>`        | Name of the package (required).                                |
| `--build-type`          | Specifies the build type (`ament_cmake`, `ament_python`).      |
| `--dependencies`        | Lists package dependencies.                                   |
| `--license`             | Sets the license for the package.                              |
| `--description`         | Adds a description for the package.                            |
| `--maintainer-email`    | Email address of the package maintainer.                       |
| `--maintainer-name`     | Name of the package maintainer.                                |
| `--node-name`           | Specifies a default node name for the package.                 |

